apiVersion: v1
entries:
  home-assistant:
  - apiVersion: v2
    appVersion: 2025.12.3
    created: "2025-12-16T19:52:08.269934035+01:00"
    description: Automatically Updated Helm Chart for Home Assistant
    digest: e8e4f67d9593a3f7616b19488cd6405507efe8e1afc0dfb815fdb01da33d7d9f
    home: https://github.com/pajikos/home-assistant-helm-chart
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
    keywords:
    - home-assistant
    - hass
    - homeassistant
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: sklenar.pav@gmail.com
      name: pajikos
    name: home-assistant
    sources:
    - https://github.com/pajikos/home-assistant-helm-chart
    - https://github.com/cdr/code-server
    - https://github.com/pajikos/home-assistant-helm-chart/tree/main/charts/home-assistant
    type: application
    urls:
    - home-assistant-0.3.35.tgz
    version: 0.3.35
generated: "2025-12-16T19:52:08.267722533+01:00"
